### ISSUE TITLE
Question: AVIF input with dimensions that are not a multiple of 8

### ISSUE THREAD

**Issue by lovell** [strukturag/libheif#232] opened 2020-06-11 16:03 UTC
Hello, processing the [cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.avif](https://github.com/AOMediaCodec/av1-avif/blob/master/testFiles/Netflix/avif/cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.avif) sample image with libheif:

- `heif_image_handle_get_height( heif_handle )` returns 858
- `heif_image_get_height( heif_image, heif_channel_interleaved )` returns 864

I suspect this may be due to the AV1 decoder working with 8x8 blocks internally.

The `heif-info` tool appears to use the former (from the `ispe` box?):

```sh
$ heif-info cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.avif
MIME type: unknown
image: 2048x858 (id=1), primary
  color profile: nclx
  alpha channel: no
  depth channel: no
```

The `heif-convert` tool appears to use the latter:

```sh
$ heif-convert cosmos_frame01000_yuv420_10bpc_bt2020_hlg_q50.avif out.png && file out.png 
File contains 1 images
Written to out.png
out.png: PNG image data, 2048 x 864, 16-bit/color RGB, non-interlaced
```

Note the pixel "stretching" at the bottom of this output from row 859 onwards:

![out](https://user-images.githubusercontent.com/210965/84408738-6a361f80-ac04-11ea-8a3d-ba227c217482.png)

Is this difference in dimensions the expected behaviour of libheif's public API and CLI tools?

**Comment by farindk** [comment] 2020-06-11 18:10
Hello.
Right, this AVIF seems to store a different dimension in the `ispe` box than the actual compressed image has. I will have to dive into the AVIF / AV1 standards to check whether that is correct. Obviously, the image in AV1 format is extended at the bottom to get a multiple of 8, 16, or 32.
Either the crop window in the AV1 is not specified, or a crop transformation is missing in the AVIF, or AV1 implicitly assumes that the image is cropped to the `ispe` size.

**Comment by novomesk** [comment] 2020-07-23 13:25
I am facing the similar situation in libheif-based GIMP plug-in.
```
heif-info fox.profile2.12bpc.yuv422.monochrome.odd-width.odd-height.avif 
MIME type: image/avif
image: 1203x799 (id=1), primary
  color profile: no
  alpha channel: no
  depth channel: no
```
But in GIMP I have 1208x800 and the green line on the right:
![gimp-fox profile2 12bpc yuv422 monochrome odd-width odd-height](https://user-images.githubusercontent.com/52529860/88290467-1fc1bb80-ccf7-11ea-800e-159cffc27341.png)

I think it should be cropped to 1203x799, the values returned by `heif_image_handle_get_width ( handle ), heif_image_handle_get_height ( handle )`

Small I perform the crop in my code or libheif will do it in the future?

**Comment by farindk** [comment] 2020-07-23 14:08
Actually, I consider this a bug in the encoder and/or specification. The `ispe` box is specified as a purely descriptive box that should not be used to trigger cropping, as that should be specified in a 'clap'. The `ispe` box should simply match output image size, but apparently the encoder specified the wrong AV1 image size. On the other hand, I am aware that e.g. h265 cannot specify odd image sizes with 4:2:0 as the image size is specified in chroma units (see #191).
Hence. libheif probably has to handle 'wrong' input by cropping according to the `ispe`.

**Comment by novomesk** [comment] 2020-07-23 16:36
For example I saved 100x100 AVIF via libheif.
libavif based applications opens it as 100x100 image as expected
But when I open the libheif-saved file via libheif again I have suddenly 104x104.

I understand that encoder(libaom) works like that. If the difference is below 8 pixels we can consider it as feature.

**Comment by farindk** [comment] 2020-07-29 13:21
I tried to add writing a 'clap' box that will remove the padded border. But the problem is that in order to write the 'clap' box, I need to know the size of the encoded image. However, that is not easily available. I've asked the rav1e whether there is a ways to get this without parsing the AV1 stream: https://github.com/xiph/rav1e/issues/2477

**Comment by farindk** [comment] 2020-07-29 13:51
For AVIF this should now be resolved with 07b7c81.
I'll still have to add a solution for HEIF, because h265 cannot store odd sized images.

**Comment by adityapatadia** [comment] 2020-07-29 14:05
Awesome, it would be great if you can do a bug-fix release.

**Comment by farindk** [comment] 2020-07-29 15:37
2f91ec1 should now handle odd image sizes well for AVIF and HEIF. It also should handle well HEIF image sizes < 16 pixels.
I'll leave this open until people have tested it and confirm that it's working.

**Comment by adityapatadia** [comment] 2020-07-31 08:30
I can test it. Should I compile develop branch and deploy it?

**Comment by farindk** [comment] 2020-07-31 10:06
Yes, please. I'd like to merge this soon to 'master' and tag a new release.

**Comment by novomesk** [comment] 2020-07-31 10:14
Loading AVIF with any dimensions works for me now. Just when saving it is cropped to a multiple of 2.

**Comment by farindk** [comment] 2020-07-31 10:30
@novomesk Right, that was still old code in the AOM encoder plugin. I've changed it in the commit above. The rav1e encoder plugin didn't do the rounding.

**Comment by lovell** [comment] 2020-07-31 13:44
@farindk I've tested the latest code on the `develop` branch and can see it is now cropping output to the `ispe` box dimensions. Thank you very much for investigating this and all your work helping to maintain libheif. I'll leave this issue open for now to allow others to confirm.

**Comment by farindk** [comment] 2020-07-31 13:52
@lovell Thanks. BTW: it is not cropping according to the `ispe` box, but there was a bug reading the displayed image resolution from libaom. When saving, it is now writing proper `clap` boxes for heif as h.265 cannot have odd image sizes and x265 does not support images <16 pixels width/height.

**Closed** 2020-07-31 14:33 UTC
Labels: work in progress

**Comment by adityapatadia** [comment] 2020-08-01 18:18
I have tried it but I get following error when I compile vips with it and try to encode image:

```heif_image.cc:146: bool heif::HeifPixelImage::add_plane(heif_channel, int, int, int): Assertion `bit_depth <= 16' failed```

**Comment by farindk** [comment] 2020-08-01 19:12
@adityapatadia Yes, sorry. During some apparently simple code cleanup, I added a wrong assert(), not related to this issue. Should be fixed now.
