### ISSUE TITLE
Conversion Issue: Color channel distorted in resulting image

### ISSUE THREAD

**Issue by abhinavkgrd** [strukturag/libheif#908] opened 2023-06-21 12:08 UTC
I am trying to convert an image using the wasm build, but the output has distorted colours.

The issue is reproducible on the hosted demo at https://strukturag.github.io/libheif/ but not reproducible with the Mac CLI client (v1.15.1) 

File - [IMG20230618143510.heic.zip](https://github.com/strukturag/libheif/files/11817320/IMG20230618143510.heic.zip)

Thanks in Advance !!

<img width="1440" alt="image" src="https://github.com/strukturag/libheif/assets/46242073/2c710611-26e5-4ab3-8316-5046eb358354">

**Comment by farindk** [comment] 2023-06-21 12:12
Probably duplicate of #528

**Closed** 2023-07-20 10:02 UTC
