### ISSUE TITLE
compilation error: 'offset 0 is out of the bounds [0, 0]'

### ISSUE THREAD

**Issue by vtorri** [strukturag/libheif#1372] opened 2024-11-07 06:24 UTC
libheif 1.19.2 on Windows. Error message:

```
C:/Documents/msys2/mingw64/include/c++/14.2.0/bits/stl_algobase.h:972:25: error: 'void* __builtin_memset(void*, int, long long unsigned int)' offset 0 is out of the bounds [0, 0] [-Werror=array-bounds=]
  972 |         __builtin_memset(__first, static_cast<unsigned char>(__tmp), __len);
      |         ~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

I can pass `-DCMAKE_COMPILE_WARNING_AS_ERROR=OFF` to remove the error and get just a warning, though.

**Comment by farindk** [comment] 2024-11-07 09:32
Duplicate of #1367.
This seems to be a false compiler warning. You can add `-DCMAKE_COMPILE_WARNING_AS_ERROR=OFF`.

**Closed by farindk** 2024-11-07 09:32 UTC
