### ISSUE TITLE
It's possible to update metadata without image data re-encoding

### ISSUE THREAD

**Issue by cgilles** [strukturag/libheif#164] opened 2019-10-12 16:06 UTC
I currently working to patch Exiv2 shared library to support HEIF format in read write using libheif.
Exif, Iptc, and Xmp metadata are supported. Reading is fully operational, Writing still todo.

https://github.com/cgilles/exiv2

Updating metadata with Exiv2 is simple : metadata chunk is prepared with change and whole chunk is replaced by new one. Exiv2 do not have codec, and don't need in fact.

So my question is : opening an existing HEIF file with libheif can be a right way to update metadata chunk as well ?

Best

Gilles Caulier

**Comment by fancycode** [comment] 2019-10-14 13:29
Duplicate of #105

**Closed by fancycode** 2019-10-14 13:29 UTC
