### ISSUE TITLE
 green color blocks 

### ISSUE THREAD

**Issue by styst** [strukturag/libheif#1379] opened 2024-11-11 08:40 UTC
Hello, when using heif-convert for image conversion, I have noticed occasional occurrences of green color blocks appearing in the image after multiple conversions of the same picture.
![aa7](https://github.com/user-attachments/assets/b443d308-6dc6-4082-95b6-91521cf65f3b)
![aa5](https://github.com/user-attachments/assets/87fd40a7-5e89-4007-a1db-03b5d3f5b702)

**Comment by bradh** [comment] 2024-11-11 10:44
Can you confirm this is with x265 and de265?

 Can you share the exact commands, along with source data to reproduce this?

It is likely in the de265 layer, but would be good to check first.

**Comment by styst** [comment] 2024-11-11 10:44
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by farindk** [comment] 2024-11-11 11:42
This looks very much like a race-condition when multiple tiles are decoded in parallel.
I could not reproduce this yet.

Can you tell me exactly which version (or commit hash) you are using and which cmake settings? Especially `ENABLE_MULTITHREADING_SUPPORT` and `ENABLE_PARALLEL_TILE_DECODING`.

**Comment by farindk** [comment] 2024-11-11 11:45
Also let me know the system (Linux, Windows, macOS).

**Comment by farindk** [comment] 2024-11-11 12:02
Ok, I managed to reproduce this. Does not happen very often with my 4 core CPU. Might be that it happens more often with more cores.

**Comment by styst** [comment] 2024-11-11 12:08
Our server has 2 core CPU. Is there any way to avoid this kind of problem

**Comment by styst** [comment] 2024-11-11 12:37
Setting the container to a single core resolved this issue for me. Thank you.

**Comment by farindk** [comment] 2024-11-11 13:45
Can you please confirm that the above commit fixes the race condition when running on multiple cores?

**Comment by styst** [comment] 2024-11-12 02:20
After verification, it has been confirmed that the above commit no longer encounters race condition issues when running on multiple cores of a CPU.

**Comment by farindk** [comment] 2024-11-12 09:40
Thank you for the report and the confirmation that it is fixed now.

**Closed by farindk** 2024-11-12 09:40 UTC
