### ISSUE TITLE
Problems reading alpha since v1.5.0

### ISSUE THREAD

**Issue by lgritz** [strukturag/libheif#143] opened 2019-08-18 18:55 UTC
I'm the author of [OpenImageIO](https://github.com/OpenImageIO/oiio), which uses libheif for its heic file I/O.

Ever since the 1.5.0 release was picked up by Homebrew a few days ago (on both my own mac laptop as well as the MacOSX instances on our Travis-CI tests), I have been seeing intermittent failures in some of my unit tests where I make a simple image of (1,1,1,1) values, write it, then read it back again and check that the read pixels were identical to the ones I wrote. It doesn't fail every time... maybe every 10th one... so it seems a bit nondeterministic.

After some investigation, it seems that the incorrectly read values are only in the alpha channel, and only the leftmost couple dozen pixels of the FIRST scanline. After that, it's always correct, and also the RGB channels always seem correct.

The writing seems to work consistently. The problem is with the read -- I can read the same file and only sometimes get the failure. I have not yet tried on other platforms (my Linux CI tests are using an older version of libheif).

Does this ring a bell? Please let me know what additional information I can provide to help you track it down.

**Comment by farindk** [comment] 2019-08-19 10:29
It might be a bug in the new color conversion pipeline. Which output format do you use? Separate RGB planes or some interleaved chroma format? Could you also please attach a test image?

**Comment by lgritz** [comment] 2019-08-19 17:15
Sample image attached. There's nothing broken about the image, it's the reading of it that's problematic. The image should be 1.0 in all channels of all pixels, but about once every 10-20 times it's read, just the alpha channel has garbled values in the first scanline.

[image.zip](https://github.com/strukturag/libheif/files/3516895/image.zip)

Just one source file has all of the heif reading code we have, it's pretty straightforward. The important bits are
https://github.com/OpenImageIO/oiio/blob/master/src/heif.imageio/heifinput.cpp#L118
https://github.com/OpenImageIO/oiio/blob/master/src/heif.imageio/heifinput.cpp#L178
https://github.com/OpenImageIO/oiio/blob/master/src/heif.imageio/heifinput.cpp#L248

**Comment by lgritz** [comment] 2019-08-19 17:16
By the way, thanks so much for libheif. It's been really flawless for us up until this little glitch.

**Comment by farindk** [comment] 2019-08-21 19:55
Thanks for the test image. Yes, I understand that the image is ok. However, it may help me reproduce the issue. Maybe it can also be added to our CI tests since I am not running macOS.
I'll have a look...

**Comment by lgritz** [comment] 2019-08-21 20:00
Just to be clear -- I'm by no means confident that it's OSX specific. On my OSX CI tests, I use Homebrew, so it just picks up the latest release of libheif. On my Linux CI tests, I use a specific installed version that I haven't yet updated. For all I know, 1.5 may have the same problem on all platforms. The only place I've tested it so far is OSX.

**Comment by farindk** [comment] 2019-08-27 10:10
The issue was due to a bug in changes in the image memory allocation. It is fixed now in the master branch.

**Closed by farindk** 2019-08-27 10:10 UTC

**Comment by farindk** [comment] 2019-08-27 20:24
Yes. We'll do a 1.5.1 this week.
