### ISSUE TITLE
JPEG to AVIF conversion outputs black image

### ISSUE THREAD

**Issue by adityapatadia** [strukturag/libheif#264] opened 2020-07-29 11:15 UTC
I have tried converting this image with following command
https://demo.gumlet.io/sea.jpeg

`heif-enc sea.jpeg -A -o sea.avif`

It gives black image output. I have compiled latest version of libheif along with 2.0 version of libaom.

**Comment by adityapatadia** [comment] 2020-07-29 11:17
I should mention that HEIF output works fine. The issue happens only with AVIF.

**Comment by farindk** [comment] 2020-07-29 11:25
What is 'latest version' ? v1.7.0, top of 'master' branch, top of 'develop' branch?

I see nothing special about that file. It encodes well for me.
A completely black output also seems strange to me. I have no idea how that could happen.
I'll need more specific information to reproduce this.

**Comment by adityapatadia** [comment] 2020-07-29 11:28
I used 1.7.0 of libheif. I also used 2.0.0 version of libaom.

This is how I compiled.

```
# compile libaom
  wget https://aomedia.googlesource.com/aom/+archive/bb35ba9148543f22ba7d8642e4fbd29ae301f5dc.tar.gz && \
  mkdir libaom && \
  tar -xf bb35ba9148543f22ba7d8642e4fbd29ae301f5dc.tar.gz --directory libaom  && \
  cd libaom && mkdir aom_build && \
  cd aom_build && cmake ../ -DENABLE_DOCS=0 -DENABLE_TESTS=0 -DBUILD_SHARED_LIBS=1 && \
  make -j2 V=0 && make install && \
  cd ../.. && rm -rf libaom; \
  \
# compile libheif
  tar -xf libheif-1.7.0.tar.gz && \
  cd libheif-1.7.0 && ./configure && \
  make -j2 V=0 && make install && \
  cd .. && rm -rf libheif-1.7.0; \

```

**Comment by adityapatadia** [comment] 2020-07-29 11:28
I am ready to provide any information you need.

**Comment by adityapatadia** [comment] 2020-07-29 11:28
This is my output file: https://transfer.sh/bSpjm/sea.avif

**Comment by farindk** [comment] 2020-07-29 11:35
Your output looks fine. This is the JPEG when I decode it back with
`heif-convert ~/sea.avif sea-decoded.jpg`

The only problem is the padding at the bottom border. Maybe your image viewer cannot handle AVIF or it is confused by this padding issue.

![sea-decoded](https://user-images.githubusercontent.com/968944/88795345-2b522e00-d1a0-11ea-85a9-d0d54d212795.jpg)

**Comment by adityapatadia** [comment] 2020-07-29 11:38
What is the reason for the padding at bottom? It's not there in original image.

> Maybe your image viewer cannot handle AVIF or it is confused by this padding issue.

My image viewer is Chrome 85 which has added support for AVIF images.

**Comment by adityapatadia** [comment] 2020-07-29 11:39
Images like this open perfectly fine in Chrome 85 Beta: https://github.com/link-u/avif-sample-images/blob/master/kimono.avif

**Comment by farindk** [comment] 2020-07-29 11:42
The padding issue is a bug / missing features (see #232). We're working on it.

**Comment by adityapatadia** [comment] 2020-07-29 11:45
Do you mean if I output height is multiple of 8, it will be resolved?

**Comment by adityapatadia** [comment] 2020-07-29 11:48
Okay, that is correct. I cropped image 800x800 and then converted it. It shows perfectly fine in Chrome 85. I will be waiting for the bug fix.

**Comment by farindk** [comment] 2020-07-29 11:50
Thanks, it is good to know that the padding is the reason for this behavior.
I'll close this issue as it appears to be in fact a duplicate of #232.

**Comment by adityapatadia** [comment] 2020-08-02 17:33
This issue is still not resolved. Please check the image produced by master branch.
[sea.avif.zip](https://github.com/strukturag/libheif/files/5012521/sea.avif.zip)

**Comment by farindk** [comment] 2020-08-03 09:29
Hm, when I encode that image (input size 713x476) with current libheif, master branch, the image shows correctly in Chroma 85 beta (Linux). Image attached.
[sea-small.zip](https://github.com/strukturag/libheif/files/5015061/sea-small.zip)

**Comment by adityapatadia** [comment] 2020-08-04 19:24
I have checked with https://github.com/strukturag/libheif/commit/0c49d5b4882bcbfc0279dede005832367eb83397 and it seems to be working perfectly fine.

**Comment by farindk** [comment] 2020-08-04 19:26
Thanks for testing again. Can we close the issue?

**Comment by adityapatadia** [comment] 2020-08-04 19:31
Yes, let's close it. Just one more suggestion. Libaom 2.0 also seems slow so I would appreciate if you write a detailed description on how to work with rav1e.

**Comment by farindk** [comment] 2020-08-04 19:36
Since there are no rav1e packages yet, you have to compile rav1e inside the source tree (see the README). Then, you have to use cmake for compilation, I have not integrated rav1e into the automake scripts yet (#266).

**Closed by farindk** 2020-08-04 19:36 UTC

**Comment by adityapatadia** [comment] 2020-08-04 20:00
Readme states that there is third-party folder but I don't see any.

**Comment by farindk** [comment] 2020-08-04 20:04
@adityapatadia Good point :-) I've just checked in the missing file...
