### ISSUE TITLE
Cant open images saved with alpha on Mac

### ISSUE THREAD

**Issue by VladimirBadalyan** [strukturag/libheif#56] opened 2018-07-31 11:45 UTC
We have address fault error on openning alpha item. And test on gimp  and error appears on gimp too.
Steps:
1. Open png image on mac Preview 
2. Save as Heic with alpha
3. Open image with gimp 

Plug-in crashed: "file-heif"
(/Applications/Gimp-2.10.app/Contents/Resources/lib/gimp/2.0/plug-ins/file-heif)

The dying plug-in may have messed up GIMP's internal state. You may want to save your images and restart GIMP to be on the safe side.
![screen shot 2018-07-31 at 3 45 19 pm](https://user-images.githubusercontent.com/14294255/43457730-cb62cb40-94d8-11e8-973d-7b845a61aabe.png)

**Comment by farindk** [comment] 2018-07-31 11:49
Thanks, Vladimir. If you have a small example image at hand, could you please attach the file here for testing?

**Comment by VladimirBadalyan** [comment] 2018-08-07 13:28
[road.heic.zip](https://github.com/strukturag/libheif/files/2266529/road.heic.zip)

**Comment by farindk** [comment] 2018-08-07 13:41
Thanks. Confirmed. Crashes in libde265 with the following assertion:

    heif-convert: image.cc:316: de265_error de265_image::alloc_image(int, int, de265_chroma, std::shared_ptr<const seq_parameter_set>, bool, decoder_context*, de265_PTS, void*, bool): Assertion `sps->SubWidthC == SubWidthC' failed.

**Comment by VladimirBadalyan** [comment] 2018-08-07 13:58
Thanks.
And I can't get alpha channel from image. The image is saved by gimp plugin and have some transparent regions.
This is code snipet  how i did. The function heif_image_handle_has_alpha_channel() always returns false. And than I call 
heif_decode_image(handle,
                            &img,
                            heif_colorspace_RGB,
                            heif_chroma_interleaved_32bit,
                            NULL);
it returns black pixels with alpha == 255. 
Please can you say there I'm wrong

int num = heif_context_get_number_of_top_level_images(ctx);
    if (num==0) {
        LOG_ERROR << "Input file contains no readable images";
        heif_context_free(ctx);
        return {};
    }

    // get the primary image
    heif_item_id primary;

    error = heif_context_get_primary_image_ID(ctx, &primary);
    if (error.code) {
        heif_context_free(ctx);
        return {};
    }

    // if primary image is no top level image or not present (invalid file), just take the first image
    if (!heif_context_is_top_level_image_ID(ctx, primary)) {
        int n = heif_context_get_list_of_top_level_image_IDs(ctx, &primary, 1);
        assert(n==1);
    }
    heif_item_id selected_image = primary;

    // load the picture
    struct heif_image_handle* handle = 0;
    error = heif_context_get_image_handle(ctx, selected_image, &handle);
    if (error.code) {
        heif_context_free(ctx);
        return {};
    }

    int has_alpha = heif_image_handle_has_alpha_channel(handle); **/Always returns _false_/**

    struct heif_image* img = 0;
    error = heif_decode_image(handle,
                            &img,
                            heif_colorspace_RGB,
                            has_alpha ? heif_chroma_interleaved_32bit :
                            heif_chroma_interleaved_24bit,
                            NULL);

**Comment by farindk** [comment] 2018-08-13 09:16
Fixed reading monochrome images (like present in `road.heic`) in libde265, master branch, commit 1c9c9730e2bcf5dcecb2b1750a832d3abe976076.
No fix necessary for 'frame-parallel' branch.

Still looking into `mountain.heic`...

**Comment by farindk** [comment] 2018-08-13 11:11
Fixed reading of tiled alpha channels (commit e68565280c944a5ebc60059ce589015a6913a748).

Your `mountain.heic` file should now read correctly and have the alpha channel assigned to the main image, instead of showing up as a second image.

**Closed** 2018-08-27 08:17 UTC

**Comment by dustymabe** [comment] 2018-12-22 15:42
I'm seeing the following abort with libheif-1.3.2 (delivered in an [rpm from rpmfusion](http://koji.rpmfusion.org/koji/buildinfo?buildID=9552))

```
heif-convert: image.cc:315: de265_error de265_image::alloc_image(int, int, de265_chroma, std::shared_ptr<const seq_parameter_set>, bool, decoder_context*, encoder_context*, de265_PTS, void*, bool): Assertion `sps->SubWidthC == SubWidthC' failed.`
```

It looks like the same error from https://github.com/strukturag/libheif/issues/56#issuecomment-411060142. If this is fixed could we get a new release of libheif so distros can pick up the new release?

**Comment by dustymabe** [comment] 2018-12-29 22:13
> I'm seeing the following abort with libheif-1.3.2 (delivered in an [rpm from rpmfusion](http://koji.rpmfusion.org/koji/buildinfo?buildID=9552))


It turns out I needed master of https://github.com/strukturag/libde265 to get around the issue I was having.
