### ISSUE TITLE
Images from Apple devices are distorted when parsed by libheif

### ISSUE THREAD

**Issue by kaatt** [strukturag/libheif#401] opened 2020-12-14 10:25 UTC
Original image:

<img width="200" alt="" src="https://user-images.githubusercontent.com/10688522/102064068-dcd6c080-3e1c-11eb-9b09-83dbe76050c9.png">

Distorted decode in https://strukturag.github.io/libheif/:

<img width="400" alt="" src="https://user-images.githubusercontent.com/10688522/102070014-8e2d2480-3e24-11eb-97e6-d3ff349c4db4.png">

Download HEIC image: [IMG_8099.heic.zip](https://github.com/strukturag/libheif/files/5688127/IMG_8099.heic.zip) (it's in zip because GitHub doesn't allow HEIC uploads)

**Comment by farindk** [comment] 2020-12-14 10:30
This has probably been fixed in d97b79f3c1657ba1497e9a549a0f0e6bb9547d11.
@fancycode Is the latest version online?

**Comment by catdad** [comment] 2020-12-14 12:43
This is a duplicate of #335 and was already fixed there, so it works in the current master. There has not been a new release since then though.

**Comment by kaatt** [comment] 2020-12-14 14:41
@catdad can you release a patch version of libheif-js (1.9.1-patch) based on libheif master? Would greatly appreciate!

**Comment by catdad** [comment] 2020-12-16 23:46
Luckily, 1.10.0 was released before I got a chance to do that. Images with odd widths work correctly there now

**Comment by farindk** [comment] 2020-12-16 23:53
@catdad :-) Yes, I wanted to get everything released before the end of the year.

**Comment by fancycode** [comment] 2020-12-17 07:42
Just updated https://strukturag.github.io/libheif/ to libheif 1.10.0, the image now renders correctly.

**Closed by fancycode** 2020-12-17 07:42 UTC
