### ISSUE TITLE
testing fails with 1bit/2color PNG sample to heif

### ISSUE THREAD

**Issue by zedd-0** [strukturag/libheif#969] opened 2023-09-30 09:03 UTC
Hello,
I tried feeding HEIF with 1-bit graphics.
I viewed the image with XnView and decoded it with heif-convert.
What I got is a corrupted image.

![expl](https://github.com/strukturag/libheif/assets/72569222/a5f9a324-1f32-4160-b4df-ff66e777c277)
![test](https://github.com/strukturag/libheif/assets/72569222/3b981b16-1459-4a35-9d16-1d367ab6dbbf)

**Comment by bradh** [comment] 2023-09-30 09:34
Can you provide detailed reproduction steps? Source file, exact conversion / processing, validation.

**Comment by farindk** [comment] 2023-09-30 11:52
I've added support for palette color PNGs some time ago. When I try the image above with the current master branch, it works fine. It does not work with the current release v1.16.2, though.

If you find an image that doesn't work with the current `master` branch, please attach it, otherwise I think we can close this as already fixed.

**Comment by zedd-0** [comment] 2023-09-30 12:53
source file is the second picture in my 1st post.

command is simple:
heif-enc.exe -q 40 -o "%~dpn1_out.heif" "%~1"
heif-enc.exe" --avif -q 40 -o "%~dpn1_out.heif" "%~1"

avif fails completely.

**Comment by farindk** [comment] 2023-09-30 13:21
Yes, I've tried with that picture. Works with the current master branch.

**Comment by zedd-0** [comment] 2023-09-30 13:22
when will the fixed version released?
i'm sill on v1.16.2

**Comment by farindk** [comment] 2023-09-30 13:24
Not sure yet when I have the time, but it is definitely time for a new release.

**Closed by farindk** 2023-09-30 13:24 UTC

**Comment by zedd-0** [comment] 2023-09-30 13:26
i have an other glitch, too.

![256 png_q050-420 m5](https://github.com/strukturag/libheif/assets/72569222/8b797f41-0628-4eee-bd7b-b9c31298f792)
avif, Q=50 chroma=auto
![256 png_q050-420 m5](https://github.com/strukturag/libheif/assets/72569222/13039fa7-28d1-46ef-af3b-574869fbbc64)

**Comment by farindk** [comment] 2023-09-30 15:17
Concerning the second issue: it is clear that it is because of the last chroma line as the input image has an odd image height. However, I cannot reproduce this with the current master branch. I tried all av1 encoders (aom, rav1e, svt) and never got this problem.

Please give full information how to reproduce this: the exact command line, the output of `heif-enc --list-encoders`, and the libheif version or commit hash.

**Comment by zedd-0** [comment] 2023-09-30 17:23
i used the default encoder. --> (aom)
if you say it is fixed in the maser branch,
i will wait for the next release.

**Comment by zedd-0** [comment] 2023-10-17 20:12
using: libheif - 2023-10-17 - v1.17.0-1-mingw - win64-x86
testpicture orginal (300x225):
![271775528-d0ae8b0a-cc9e-4c5b-a734-9836804ec9df](https://github.com/strukturag/libheif/assets/72569222/dded8287-d956-4a61-8c39-06a9f68f2d07)

test with AVIF output:  300x225 / ok

test with HEIG output: 300x224 / wrong
- last line was removed
![271775528-d0ae8b0a-cc9e-4c5b-a734-9836804ec9df png_z100-444 ll heif_dec](https://github.com/strukturag/libheif/assets/72569222/7f709638-56c3-47d6-b115-1367f843a837)
